Add missing declaration for functions
Without these, the compiler failed with `error: implicit declaration of function 'caml_rev_convert_signal_number' is invalid in C99`